# Generated by Django 3.2.15 on 2022-11-14 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0013_includedlink'),
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_bookmarks', to='twitter.twitteraccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containing_bookmarks', to='twitter.tweet'),
        ),
    ]
