# Generated by Django 3.2.15 on 2022-11-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_auto_20221114_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
