# Generated by Django 3.2.13 on 2022-06-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='client id'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='client secret'),
        ),
    ]
