# Generated by Django 3.2.13 on 2022-07-10 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_clientaccount_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='refreshed',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 10, 1, 9, 12, 946745), verbose_name='time the token was refreshed'),
        ),
    ]
