# Generated by Django 3.2.13 on 2022-07-10 01:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_clientaccount_refreshed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccount',
            name='refreshed',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 10, 1, 9, 55, 886852, tzinfo=utc), verbose_name='time the token was refreshed'),
        ),
    ]
