# Generated by Django 3.2.13 on 2022-07-10 01:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_clientaccount_refreshed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccount',
            name='refreshed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time the token was refreshed'),
        ),
    ]
