# Generated by Django 3.2.13 on 2022-07-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20220717_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bearer_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='bearer token'),
        ),
    ]
