# Generated by Django 3.2.13 on 2022-07-20 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_group'),
        ('client', '0011_client_bearer_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='twitter_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='twitter.twitteraccount'),
        ),
    ]
