# Generated by Django 3.2.13 on 2022-07-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_client_auth_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='access_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='oauth v1 access key'),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='secret_access_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='oauth v2 secret key'),
        ),
    ]
