# Generated by Django 3.2.13 on 2022-08-05 17:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_rename_follows_twitteraccount_following'),
        ('client', '0014_auto_20220729_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='twitter oauth2 token')),
                ('refresh_token', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='twitter oauth2 refresh token')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='account email address')),
                ('refreshed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time the token was refreshed')),
                ('access_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='oauth v1 access key')),
                ('secret_access_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='oauth v2 secret key')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='client.client')),
                ('twitter_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_accounts', to='twitter.twitteraccount')),
            ],
        ),
    ]
