# Generated by Django 3.2.13 on 2022-09-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_staffaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_preference', models.CharField(choices=[('TW', 'Tweet'), ('EM', 'Email'), ('DM', 'Direct Message')], default='TW', max_length=2)),
                ('notification_requested', models.BooleanField(default=False, verbose_name='Has the user requested notification?')),
                ('client_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='client.clientaccount')),
            ],
        ),
    ]
