# Generated by Django 3.2.13 on 2022-09-04 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_accountconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountconfig',
            name='client_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='client.clientaccount'),
        ),
    ]
