# Generated by Django 3.2.15 on 2022-10-05 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0012_accounterror'),
        ('client', '0017_alter_accountconfig_client_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccount',
            name='twitter_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_accounts', to='twitter.twitteraccount'),
        ),
    ]
