# Generated by Django 3.2.16 on 2023-02-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_alter_clientaccount_twitter_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='stripe customer id'),
        ),
    ]
