# Generated by Django 3.2.13 on 2022-06-20 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=512, unique=True, verbose_name='Tweet ID')),
                ('tweet_created_at', models.DateTimeField(verbose_name='Datetime that tweet was created')),
                ('message', models.CharField(max_length=512, verbose_name='Content of the Tweet')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id', models.CharField(max_length=512, unique=True, verbose_name='the twitter id of the user')),
                ('twitter_username', models.CharField(blank=True, max_length=512, null=True, verbose_name='the username of the user')),
                ('twitter_name', models.CharField(blank=True, max_length=512, null=True, verbose_name='the name of the user')),
                ('twitter_bio', models.CharField(blank=True, max_length=1024, null=True, verbose_name='the bio of the user')),
                ('twitter_profile_picture_url', models.CharField(blank=True, max_length=1024, null=True, verbose_name="the url of the user's profile picture")),
            ],
        ),
        migrations.CreateModel(
            name='TweetCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='the name of the collection')),
                ('tweets', models.ManyToManyField(related_name='collections', to='twitter.Tweet')),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.twitteraccount'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='in_response_to',
            field=models.ManyToManyField(related_name='responses', to='twitter.Tweet'),
        ),
        migrations.CreateModel(
            name='Retweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retweeting_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retweeted_tweets', to='twitter.twitteraccount')),
                ('tweet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retweets', to='twitter.tweet')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liking_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_tweets', to='twitter.twitteraccount')),
                ('tweet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='twitter.tweet')),
            ],
        ),
    ]
