# Generated by Django 3.2.13 on 2022-06-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_twitteraccount_most_recent_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteraccount',
            name='follows',
            field=models.ManyToManyField(to='twitter.TwitterAccount'),
        ),
    ]
