# Generated by Django 3.2.13 on 2022-06-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_twitteraccount_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteraccount',
            name='last_tweet_date',
            field=models.DateTimeField(null=True, verbose_name='date of last tweet'),
        ),
        migrations.AlterField(
            model_name='twitteraccount',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='twitter.TwitterAccount'),
        ),
    ]
