# Generated by Django 3.2.13 on 2022-07-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteraccount',
            name='last_checked',
            field=models.DateField(null=True, verbose_name='date followers and following looked up'),
        ),
    ]
