# Generated by Django 3.2.13 on 2022-08-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_rename_follows_twitteraccount_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteraccount',
            name='protected',
            field=models.BooleanField(default=False, verbose_name='is the account protected'),
        ),
    ]
