# Generated by Django 3.2.13 on 2022-08-07 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_twitteraccount_protected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follows_this_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explicit_followed_by', to='twitter.twitteraccount')),
                ('this_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explicit_following', to='twitter.twitteraccount')),
            ],
        ),
        migrations.AddField(
            model_name='twitteraccount',
            name='relationships',
            field=models.ManyToManyField(related_name='related_to', through='twitter.Relationship', to='twitter.TwitterAccount'),
        ),
    ]
