# Generated by Django 3.2.13 on 2022-08-07 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0009_auto_20220807_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteraccount',
            name='following',
        ),
    ]
