# Generated by Django 3.2.13 on 2022-09-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0010_remove_twitteraccount_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='twitter.tweet')),
            ],
        ),
    ]
