# Generated by Django 3.2.15 on 2022-11-13 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0012_accounterror'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncludedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1024, verbose_name='Link included in tweet')),
                ('original_image_url', models.CharField(blank=True, max_length=1024, null=True, verbose_name='URL of the image that was included in the tweet')),
                ('thumbnail_image_url', models.CharField(blank=True, max_length=1024, null=True, verbose_name='URL of the thumbnail image that was included in the tweet')),
                ('title', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Title of the page that was linked to')),
                ('includingTweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_links', to='twitter.tweet')),
            ],
        ),
    ]
