# Generated by Django 3.2.16 on 2022-12-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_toolkit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='transcript_embeddings',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='key_points',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='linkedin_post',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='links_to_include',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='twitter_thread',
            field=models.TextField(null=True),
        ),
    ]
