# Generated by Django 3.2.13 on 2022-06-15 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=512, verbose_name='Tweet ID')),
                ('action', models.CharField(max_length=512, verbose_name='Action To Take')),
                ('cadence', models.CharField(max_length=512, verbose_name='Cadence of checking')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyToTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_twitter_id', models.CharField(max_length=512, verbose_name='Twitter ID of respondent')),
                ('response_id', models.CharField(max_length=512, verbose_name='Tweet ID of response')),
                ('responded', models.BooleanField(default=False, verbose_name='Have we responded to this response')),
                ('tweet_responded_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='respondents', to='watchtweet.watchtweet')),
            ],
        ),
    ]
