# Generated by Django 3.2.13 on 2022-06-16 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchtweet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1024, verbose_name='Question to ask users')),
            ],
        ),
        migrations.CreateModel(
            name='PromptResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.BooleanField(default=False, verbose_name='did the user respond yes to prompt')),
                ('twitter_id', models.CharField(max_length=512, verbose_name='twitter Id of respondant')),
                ('responded_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='watchtweet.watchtweet')),
            ],
        ),
        migrations.AddField(
            model_name='watchtweet',
            name='prompt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompted_tweets', to='watchtweet.promptquestion'),
        ),
    ]
