# Generated by Django 3.2.13 on 2022-06-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchtweet', '0002_auto_20220616_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptquestion',
            name='question',
            field=models.CharField(max_length=280, verbose_name='Question to ask users'),
        ),
    ]
