# Generated by Django 3.2.13 on 2022-06-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchtweet', '0003_alter_promptquestion_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='replytotweet',
            name='message',
            field=models.CharField(default='message', max_length=280, verbose_name='text of response'),
            preserve_default=False,
        ),
    ]
