# Generated by Django 3.2.13 on 2022-06-17 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchtweet', '0004_replytotweet_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replytotweet',
            name='tweet_responded_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respondents', to='watchtweet.watchtweet'),
        ),
    ]
