# Generated by Django 3.2.13 on 2022-06-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchtweet', '0005_alter_replytotweet_tweet_responded_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replytotweet',
            name='message',
            field=models.CharField(max_length=1024, verbose_name='text of response'),
        ),
    ]
