# Generated by Django 3.2.13 on 2022-06-18 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchtweet', '0008_alter_watchtweet_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchtweet',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompted_tweets', to='watchtweet.promptquestion'),
        ),
    ]
