# Generated by Django 3.2.13 on 2022-06-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchtweet', '0009_alter_watchtweet_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchtweet',
            name='children',
        ),
        migrations.AddField(
            model_name='watchtweet',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='parent', to='watchtweet.WatchTweet'),
        ),
    ]
