# Generated by Django 3.2.13 on 2022-07-04 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20220628_0138'),
        ('watchtweet', '0014_accountstoignore_accountthatrespondedtowatchedtweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweettowatch',
            name='action_to_take',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweets_to_act_on', to='watchtweet.action'),
        ),
        migrations.AlterField(
            model_name='tweettowatch',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watches_requested', to='twitter.twitteraccount'),
        ),
    ]
