# Generated by Django 3.2.13 on 2022-08-05 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twitter', '0007_rename_follows_twitteraccount_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='the name of the subscription')),
                ('cadence', models.CharField(choices=[('DL', 'Daily'), ('WK', 'Weekly')], default='WK', max_length=2)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='twitter.group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='twitter.twitteraccount')),
            ],
        ),
    ]
