# Generated by Django 3.2.15 on 2022-10-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentfeed',
            name='url',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='link to the content'),
        ),
    ]
