# Generated by Django 3.2.15 on 2022-10-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_alter_contentfeed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('BL', 'Requested'), ('YT', 'In progress'), ('VD', 'Complete'), ('PC', 'Error')], default='BL', max_length=2),
        ),
    ]
