# Generated by Django 3.2.15 on 2022-10-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0003_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='image for the content'),
        ),
    ]
