# Generated by Django 3.2.13 on 2022-07-21 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendcontent', '0003_triggertweet_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggertweet',
            name='child',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='friendcontent.triggertweet'),
        ),
    ]
