# Generated by Django 3.2.13 on 2022-07-03 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twitter', '0004_auto_20220628_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.IntegerField(default=5, verbose_name='how many levels deep to search')),
                ('completed', models.BooleanField(default=False, verbose_name='has the crawler finished')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawls', to='twitter.twitteraccount')),
            ],
        ),
        migrations.CreateModel(
            name='CrawledAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_crawl', models.DateField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawled_on', to='twitter.twitteraccount')),
                ('starting_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawled_from', to='crawler.startingaccount')),
            ],
        ),
    ]
