# Generated by Django 3.2.13 on 2022-05-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfollow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteraccount',
            name='token',
            field=models.CharField(max_length=100, null=True, verbose_name='Token'),
        ),
    ]
