# Generated by Django 3.2.13 on 2022-06-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfollow', '0002_twitteraccount_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Group Name')),
                ('members', models.ManyToManyField(related_name='member_of', to='unfollow.TwitterAccount')),
            ],
        ),
        migrations.AddField(
            model_name='twitteraccount',
            name='groups',
            field=models.ManyToManyField(related_name='owned_by', to='unfollow.Group'),
        ),
    ]
