# Generated by Django 3.2.13 on 2022-07-07 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_group'),
        ('unfollow', '0007_alter_analysis_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='twitter.twitteraccount', unique=True),
        ),
    ]
