# Generated by Django 3.2.13 on 2022-07-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfollow', '0010_alter_analysis_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='state',
            field=models.CharField(choices=[('RE', 'Requested'), ('IP', 'In progress'), ('CP', 'Complete'), ('ER', 'Error')], default='RE', max_length=2),
        ),
    ]
