# Generated by Django 3.2.13 on 2022-07-26 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_rename_follows_twitteraccount_following'),
        ('client', '0012_client_twitter_account'),
        ('unfollow', '0013_accountcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnfollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unfollowed', models.DateTimeField(null=True, verbose_name='the time the account was unfollowed')),
                ('account_to_unfollow', models.ManyToManyField(related_name='unfollow_requests', to='twitter.TwitterAccount')),
                ('requesting_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_unfollows', to='client.clientaccount')),
            ],
        ),
    ]
