# Generated by Django 3.2.13 on 2022-07-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20220717_0158'),
        ('unfollow', '0014_remove_accountcheck_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountcheck',
            name='requests',
        ),
        migrations.AddField(
            model_name='accountcheck',
            name='requests',
            field=models.ManyToManyField(related_name='accounts_to_analyze', to='client.ClientAccount'),
        ),
    ]
