# Generated by Django 3.2.13 on 2022-07-26 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_rename_follows_twitteraccount_following'),
        ('unfollow', '0014_unfollowrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unfollowrequest',
            name='account_to_unfollow',
        ),
        migrations.AddField(
            model_name='unfollowrequest',
            name='account_to_unfollow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unfollow_requests', to='twitter.twitteraccount'),
        ),
    ]
