# Generated by Django 3.2.13 on 2022-09-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfollow', '0015_auto_20220726_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcheck',
            name='error',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Error encountered'),
        ),
    ]
