# Generated by Django 3.2.13 on 2022-09-21 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unfollow', '0018_accounterror'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountError',
        ),
    ]
