# Generated by Django 3.2.16 on 2023-01-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effortless_reach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='error',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='status',
            field=models.CharField(choices=[('RE', 'Requested'), ('PR', 'Processing'), ('CO', 'Completed'), ('FA', 'Failed')], default='RE', max_length=2),
        ),
    ]
