# Generated by Django 3.2.16 on 2023-01-29 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('effortless_reach', '0002_auto_20230128_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='rss_feed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='podcast', to='effortless_reach.rssfeed'),
        ),
    ]
