# Generated by Django 3.2.16 on 2023-01-30 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('effortless_reach', '0003_alter_podcast_rss_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('PR', 'Processing'), ('CO', 'Completed'), ('FA', 'Failed')], default='PE', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error', models.TextField(null=True)),
                ('podcast_episode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_requested', to='effortless_reach.podcastepisode')),
            ],
        ),
    ]
