# Generated by Django 3.2.16 on 2023-02-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effortless_reach', '0004_transcriptrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='hash',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
