# Generated by Django 3.2.16 on 2023-02-09 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('effortless_reach', '0005_transcript_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('embeddings', models.JSONField(blank=True, null=True)),
                ('embeddings_saved', models.BooleanField(default=False)),
                ('chunk_id', models.CharField(max_length=255, unique=True)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='effortless_reach.transcript')),
            ],
        ),
    ]
