# Generated by Django 3.2.16 on 2023-02-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effortless_reach', '0006_transcriptchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='image',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='image',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
