# Generated by Django 3.2.16 on 2023-02-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effortless_reach', '0007_auto_20230212_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='transformed_link',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
