# Generated by Django 3.2.16 on 2023-02-25 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('effortless_reach', '0008_podcastepisode_transformed_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('error', models.TextField(null=True)),
                ('episode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='effortless_reach.podcastepisode')),
            ],
        ),
        migrations.CreateModel(
            name='KeyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('error', models.TextField(null=True)),
                ('episode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='key_points', to='effortless_reach.podcastepisode')),
            ],
        ),
    ]
