# Generated by Django 3.2.15 on 2022-12-03 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twitter', '0013_includedlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='twitter.twitteraccount', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FollowerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date of report')),
                ('followers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_following', to='twitter.twitteraccount')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='followed.subscriber')),
            ],
        ),
    ]
