# Generated by Django 3.2.15 on 2022-12-03 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_alter_clientaccount_twitter_account'),
        ('followed', '0002_alter_subscriber_twitter_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='twitter_account',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='client_account',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followed_subscription', to='client.clientaccount'),
            preserve_default=False,
        ),
    ]
