# Generated by Django 3.2.15 on 2022-12-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followed', '0005_subscriber_subscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='beta',
            field=models.BooleanField(default=False, verbose_name='is this a beta account'),
        ),
    ]
