# Generated by Django 3.2.16 on 2022-12-20 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enhancer', '0003_enhancedtwitteraccount_likely_spam'),
        ('twitter', '0013_includedlink'),
        ('followed', '0006_subscriber_beta'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifferenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, verbose_name='date of report')),
                ('sent', models.BooleanField(default=False, verbose_name='has this report been sent')),
                ('lost_followers', models.ManyToManyField(related_name='stopped_following', to='twitter.TwitterAccount')),
                ('new_followers', models.ManyToManyField(related_name='new_followers', to='enhancer.EnhancedTwitterAccount')),
                ('newer_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newer_report', to='followed.followerreport')),
                ('older_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='older_report', to='followed.followerreport')),
            ],
        ),
    ]
