# Generated by Django 3.2.16 on 2022-12-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followed', '0008_auto_20221220_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='differencereport',
            name='date',
            field=models.DateTimeField(verbose_name='date of report'),
        ),
    ]
