# Generated by Django 3.2.18 on 2023-03-14 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leoai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leoai.message'),
        ),
    ]
