# Generated by Django 3.2.18 on 2023-03-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leoai', '0003_collection_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
