# Generated by Django 3.2.16 on 2022-12-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAICall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_used', models.IntegerField()),
                ('source', models.CharField(max_length=255)),
                ('request_id', models.IntegerField()),
                ('request_type', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('parent_id', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
