# Generated by Django 3.2.16 on 2022-12-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaicall',
            name='request_id',
            field=models.CharField(max_length=255),
        ),
    ]
