# Generated by Django 3.2.16 on 2023-01-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
