# Generated by Django 3.2.16 on 2023-01-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
