# Generated by Django 3.2.16 on 2023-01-06 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_content_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='search.content')),
            ],
        ),
    ]
