# Generated by Django 3.2.16 on 2023-01-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_contentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentchunk',
            name='embeddings_saved',
            field=models.BooleanField(default=False),
        ),
    ]
