# Generated by Django 3.2.16 on 2023-01-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_contentchunk_embeddings_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentchunk',
            name='embeddings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
