# Generated by Django 3.2.16 on 2023-01-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_contentchunk_embeddings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentchunk',
            name='chunk_id',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
