# Generated by Django 3.2.16 on 2023-02-11 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_alter_clientaccount_twitter_account'),
        ('effortless_reach', '0006_transcriptchunk'),
        ('search', '0008_content_fulltext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curation', to='client.clientaccount')),
                ('podcast_episodes', models.ManyToManyField(related_name='curators', to='effortless_reach.PodcastEpisode')),
                ('podcasts', models.ManyToManyField(related_name='curators', to='effortless_reach.Podcast')),
            ],
        ),
    ]
