# Generated by Django 3.2.15 on 2022-12-11 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twitter', '0013_includedlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnhancedTwitterAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('analysis', models.JSONField(blank=True, null=True)),
                ('enhancement_run_at', models.DateTimeField(blank=True, null=True)),
                ('twitter_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.twitteraccount')),
            ],
        ),
    ]
