# Generated by Django 3.2.15 on 2022-12-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enhancer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enhancedtwitteraccount',
            name='status',
            field=models.CharField(choices=[('OK', 'Okay'), ('ER', 'Error')], default='OK', max_length=2),
        ),
    ]
