# Generated by Django 3.2.15 on 2022-12-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enhancer', '0002_enhancedtwitteraccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enhancedtwitteraccount',
            name='likely_spam',
            field=models.BooleanField(default=False),
        ),
    ]
