# Generated by Django 3.2.16 on 2022-12-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enhancer', '0005_enhancedtweetsgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='enhancedtweet',
            name='sentiment',
            field=models.CharField(choices=[('PS', 'Positive'), ('NG', 'Negative'), ('NU', 'Neutral')], default='NU', max_length=2),
        ),
    ]
